// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/whj1990/app-mine/internal/repo"
	"github.com/whj1990/app-mine/internal/service"
	"github.com/whj1990/go-core/store"
	"github.com/whj1990/go-core/trace"
)

// Injectors from wire.go:

func initServer() (server.Server, error) {
	loggerInterface := trace.NewGormLogger()
	db, err := store.NewDB(loggerInterface)
	if err != nil {
		return nil, err
	}
	reviewProjectRepo := repo.NewReviewProjectRepo(db)
	reviewService := service.NewReviewService(reviewProjectRepo)
	appMine := newAppMineImpl(reviewService)
	serverServer := newServer(appMine)
	return serverServer, nil
}
