// Code generated by Kitex v0.4.3. DO NOT EDIT.

package appmine

import (
	api "app-mine/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ReviewProjectList(ctx context.Context, req *api.ReviewProjectListParams, callOptions ...callopt.Option) (r *api.ReviewProjectListResponse, err error)
	ReviewProjectDetails(ctx context.Context, req *api.IdsInt64Params, callOptions ...callopt.Option) (r *api.ReviewProjectDetailResponse, err error)
	ReviewProjectSave(ctx context.Context, req *api.ReviewProjectSaveParam, callOptions ...callopt.Option) (r *api.SaveResponse, err error)
	ReviewProjectStatus(ctx context.Context, req *api.StatusParam, callOptions ...callopt.Option) (r *api.SaveResponse, err error)
	ReviewProjectDelete(ctx context.Context, req *api.IdParam, callOptions ...callopt.Option) (r *api.SaveResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAppMineClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAppMineClient struct {
	*kClient
}

func (p *kAppMineClient) ReviewProjectList(ctx context.Context, req *api.ReviewProjectListParams, callOptions ...callopt.Option) (r *api.ReviewProjectListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewProjectList(ctx, req)
}

func (p *kAppMineClient) ReviewProjectDetails(ctx context.Context, req *api.IdsInt64Params, callOptions ...callopt.Option) (r *api.ReviewProjectDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewProjectDetails(ctx, req)
}

func (p *kAppMineClient) ReviewProjectSave(ctx context.Context, req *api.ReviewProjectSaveParam, callOptions ...callopt.Option) (r *api.SaveResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewProjectSave(ctx, req)
}

func (p *kAppMineClient) ReviewProjectStatus(ctx context.Context, req *api.StatusParam, callOptions ...callopt.Option) (r *api.SaveResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewProjectStatus(ctx, req)
}

func (p *kAppMineClient) ReviewProjectDelete(ctx context.Context, req *api.IdParam, callOptions ...callopt.Option) (r *api.SaveResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewProjectDelete(ctx, req)
}
